apiVersion: v1
kind: Secret
metadata:
  name: nginx-secretos
  namespace: practica
type: Opaque
# stringData: texto plano. Kubernetes lo convierte a base64 en data.
stringData:
  usuario: adso
  password: secreto123
  token: mi-token-de-practica
