apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-volumen
  namespace: practica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
