apiVersion: v1
kind: Pod
metadata:
  name: mi-primer-pod
  namespace: practica
  labels:
    app: nginx-ejemplo
    tier: ejemplo
spec:
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      env:
        - name: MI_VARIABLE
          value: "hola"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
