apiVersion: v1
kind: Pod
metadata:
  name: app-con-volumen
  namespace: practica
spec:
  containers:
    - name: app
      image: nginx:1.25
      volumeMounts:
        - name: almacenamiento
          mountPath: /usr/share/nginx/html
  volumes:
    - name: almacenamiento
      persistentVolumeClaim:
        claimName: nginx-volumen
